# Generated by Django 3.1.6 on 2021-02-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='shopping_list',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopping_list',
            name='items',
            field=models.ManyToManyField(blank=True, to='shoppinglist.item'),
        ),
    ]
