# Generated by Django 3.1.6 on 2021-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20210222_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopping_list',
            new_name='ShoppingList',
        ),
    ]
